# Player-related constants.
PLAYER_FRICTION_COEFFICIENT = 0.95
PLAYER_MOVEMENT_SPEED = 12.5
PLAYER_JUMPING_SPEED = 400

# World/level constants.
TILE_SIZE = 32
WORLD_GRAVITY = -9.8 * TILE_SIZE
BACKGROUND_COLOUR = (0, 0, 0)
