# World/level constants.
WORLD_TILE_SIZE = 32
WORLD_TILE_SHIFT = 5
WORLD_GRAVITY = -20 * WORLD_TILE_SIZE
WORLD_BACKGROUND_COLOUR = (0, 0, 0)

# Player-related constants.
PLAYER_FRICTION_COEFFICIENT = 0.9
PLAYER_MOVEMENT_SPEED = 12.5 * 3
PLAYER_HEALTH_MAX = 100
PLAYER_JUMPING_SPEED = 300
PLAYER_JETPACK_SPEED = 1250
PLAYER_JETPACK_MAX = 250 * 3
PLAYER_JETPACK_AIR_CONTROL = 2
PLAYER_DETECT_RANGE = 40 * WORLD_TILE_SIZE
SCREEN_SCALE = 2

PROJECTILE_SPEED = 200
PROJECTILE_FIRE_RATE = 0.035
