# Player-related constants.
PLAYER_FRICTION_COEFFICIENT = 0.95
PLAYER_MOVEMENT_SPEED = 12.5
PLAYER_JUMPING_SPEED = 210
PLAYER_JETPACK_SPEED = 400
PLAYER_JETPACK_MAX = 250

# World/level constants.
WORLD_TILE_SIZE = 32
WORLD_TILE_SHIFT = 5
WORLD_GRAVITY = -9.8 * WORLD_TILE_SIZE
WORLD_BACKGROUND_COLOUR = (0, 0, 0)
